name: Тестирование

on: 
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        oscript_version: [1.4.0]
        os: [windows-latest]
    name: Тестирование
    steps:
      - name: Последняя версия проекта
        uses: actions/checkout@v1
      - name: Установка OneScript
        uses: otymko/setup-onescript@master
        with:
          version: ${{ matrix.oscript_version }}
      - name: Загрузка зависимостей
        run: opm install 1testrunner && opm install asserts && opm install 1bdd && opm install gitrunner && opm install logos && opm install osparser && opm install progbar
      - name: Локальные зависимости
        run: opm install -l
      - name: Запуск тестов
        run: opm run test
